// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/tasks/services.proto

package task_tracker_tasks

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_api_tasks_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetTasksRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_api_tasks_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateTasksRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	TasksToCreate []*CreateTasksRequest_TaskPrototype `protobuf:"bytes,1,rep,name=tasks_to_create,json=tasksToCreate,proto3" json:"tasks_to_create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTasksRequest) Reset() {
	*x = CreateTasksRequest{}
	mi := &file_api_tasks_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTasksRequest) ProtoMessage() {}

func (x *CreateTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTasksRequest.ProtoReflect.Descriptor instead.
func (*CreateTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTasksRequest) GetTasksToCreate() []*CreateTasksRequest_TaskPrototype {
	if x != nil {
		return x.TasksToCreate
	}
	return nil
}

type CreateTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTasksResponse) Reset() {
	*x = CreateTasksResponse{}
	mi := &file_api_tasks_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTasksResponse) ProtoMessage() {}

func (x *CreateTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTasksResponse.ProtoReflect.Descriptor instead.
func (*CreateTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTasksResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UpdateTasksRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	TasksToUpdate []*UpdateTasksRequest_TaskPrototype `protobuf:"bytes,1,rep,name=tasks_to_update,json=tasksToUpdate,proto3" json:"tasks_to_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTasksRequest) Reset() {
	*x = UpdateTasksRequest{}
	mi := &file_api_tasks_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTasksRequest) ProtoMessage() {}

func (x *UpdateTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTasksRequest.ProtoReflect.Descriptor instead.
func (*UpdateTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTasksRequest) GetTasksToUpdate() []*UpdateTasksRequest_TaskPrototype {
	if x != nil {
		return x.TasksToUpdate
	}
	return nil
}

type UpdateTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTasksResponse) Reset() {
	*x = UpdateTasksResponse{}
	mi := &file_api_tasks_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTasksResponse) ProtoMessage() {}

func (x *UpdateTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTasksResponse.ProtoReflect.Descriptor instead.
func (*UpdateTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{5}
}

type DeleteTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTasksRequest) Reset() {
	*x = DeleteTasksRequest{}
	mi := &file_api_tasks_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTasksRequest) ProtoMessage() {}

func (x *DeleteTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTasksRequest.ProtoReflect.Descriptor instead.
func (*DeleteTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTasksRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTasksResponse) Reset() {
	*x = DeleteTasksResponse{}
	mi := &file_api_tasks_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTasksResponse) ProtoMessage() {}

func (x *DeleteTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTasksResponse.ProtoReflect.Descriptor instead.
func (*DeleteTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{7}
}

type CreateTasksRequest_TaskPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Deps          []int64                `protobuf:"varint,3,rep,packed,name=deps,proto3" json:"deps,omitempty"`
	Priority      Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=api.v1.task_tracker.tasks.Priority" json:"priority,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTasksRequest_TaskPrototype) Reset() {
	*x = CreateTasksRequest_TaskPrototype{}
	mi := &file_api_tasks_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTasksRequest_TaskPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTasksRequest_TaskPrototype) ProtoMessage() {}

func (x *CreateTasksRequest_TaskPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTasksRequest_TaskPrototype.ProtoReflect.Descriptor instead.
func (*CreateTasksRequest_TaskPrototype) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateTasksRequest_TaskPrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTasksRequest_TaskPrototype) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTasksRequest_TaskPrototype) GetDeps() []int64 {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *CreateTasksRequest_TaskPrototype) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateTasksRequest_TaskPrototype) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateTasksRequest_TaskPrototype) GetFinishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishTime
	}
	return nil
}

type UpdateTasksRequest_TaskPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Deps          []int64                `protobuf:"varint,4,rep,packed,name=deps,proto3" json:"deps,omitempty"`
	Priority      *Priority              `protobuf:"varint,5,opt,name=priority,proto3,enum=api.v1.task_tracker.tasks.Priority,oneof" json:"priority,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	FinishTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finish_time,json=finishTime,proto3,oneof" json:"finish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTasksRequest_TaskPrototype) Reset() {
	*x = UpdateTasksRequest_TaskPrototype{}
	mi := &file_api_tasks_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTasksRequest_TaskPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTasksRequest_TaskPrototype) ProtoMessage() {}

func (x *UpdateTasksRequest_TaskPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_tasks_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTasksRequest_TaskPrototype.ProtoReflect.Descriptor instead.
func (*UpdateTasksRequest_TaskPrototype) Descriptor() ([]byte, []int) {
	return file_api_tasks_services_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateTasksRequest_TaskPrototype) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTasksRequest_TaskPrototype) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTasksRequest_TaskPrototype) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTasksRequest_TaskPrototype) GetDeps() []int64 {
	if x != nil {
		return x.Deps
	}
	return nil
}

func (x *UpdateTasksRequest_TaskPrototype) GetPriority() Priority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *UpdateTasksRequest_TaskPrototype) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateTasksRequest_TaskPrototype) GetFinishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishTime
	}
	return nil
}

var File_api_tasks_services_proto protoreflect.FileDescriptor

const file_api_tasks_services_proto_rawDesc = "" +
	"\n" +
	"\x18api/tasks/services.proto\x12\x19api.v1.task_tracker.tasks\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x16api/tasks/models.proto\"-\n" +
	"\x0fGetTasksRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x03B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"I\n" +
	"\x10GetTasksResponse\x125\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1f.api.v1.task_tracker.tasks.TaskR\x05tasks\"\xaa\x03\n" +
	"\x12CreateTasksRequest\x12m\n" +
	"\x0ftasks_to_create\x18\x01 \x03(\v2;.api.v1.task_tracker.tasks.CreateTasksRequest.TaskPrototypeB\b\xfaB\x05\x92\x01\x02\b\x01R\rtasksToCreate\x1a\xa4\x02\n" +
	"\rTaskPrototype\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vdescription\x12\x12\n" +
	"\x04deps\x18\x03 \x03(\x03R\x04deps\x12?\n" +
	"\bpriority\x18\x04 \x01(\x0e2#.api.v1.task_tracker.tasks.PriorityR\bpriority\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12;\n" +
	"\vfinish_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishTime\"'\n" +
	"\x13CreateTasksResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\x98\x04\n" +
	"\x12UpdateTasksRequest\x12m\n" +
	"\x0ftasks_to_update\x18\x01 \x03(\v2;.api.v1.task_tracker.tasks.UpdateTasksRequest.TaskPrototypeB\b\xfaB\x05\x92\x01\x02\b\x01R\rtasksToUpdate\x1a\x92\x03\n" +
	"\rTaskPrototype\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\x04name\x88\x01\x01\x12.\n" +
	"\vdescription\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x01R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04deps\x18\x04 \x03(\x03R\x04deps\x12D\n" +
	"\bpriority\x18\x05 \x01(\x0e2#.api.v1.task_tracker.tasks.PriorityH\x02R\bpriority\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tstartTime\x88\x01\x01\x12@\n" +
	"\vfinish_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\n" +
	"finishTime\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_priorityB\r\n" +
	"\v_start_timeB\x0e\n" +
	"\f_finish_time\"\x15\n" +
	"\x13UpdateTasksResponse\"0\n" +
	"\x12DeleteTasksRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x03B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\x15\n" +
	"\x13DeleteTasksResponse2\xc1\x04\n" +
	"\vTaskService\x12\x81\x01\n" +
	"\bGetTasks\x12*.api.v1.task_tracker.tasks.GetTasksRequest\x1a+.api.v1.task_tracker.tasks.GetTasksResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/get_tasks\x12\x8d\x01\n" +
	"\vCreateTasks\x12-.api.v1.task_tracker.tasks.CreateTasksRequest\x1a..api.v1.task_tracker.tasks.CreateTasksResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/create_tasks\x12\x8d\x01\n" +
	"\vUpdateTasks\x12-.api.v1.task_tracker.tasks.UpdateTasksRequest\x1a..api.v1.task_tracker.tasks.UpdateTasksResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/update_tasks\x12\x8d\x01\n" +
	"\vDeleteTasks\x12-.api.v1.task_tracker.tasks.DeleteTasksRequest\x1a..api.v1.task_tracker.tasks.DeleteTasksResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/delete_tasksBAZ?github.com/bogi-lyceya-44/task-tracker/tasks;task_tracker_tasksb\x06proto3"

var (
	file_api_tasks_services_proto_rawDescOnce sync.Once
	file_api_tasks_services_proto_rawDescData []byte
)

func file_api_tasks_services_proto_rawDescGZIP() []byte {
	file_api_tasks_services_proto_rawDescOnce.Do(func() {
		file_api_tasks_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tasks_services_proto_rawDesc), len(file_api_tasks_services_proto_rawDesc)))
	})
	return file_api_tasks_services_proto_rawDescData
}

var file_api_tasks_services_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_tasks_services_proto_goTypes = []any{
	(*GetTasksRequest)(nil),                  // 0: api.v1.task_tracker.tasks.GetTasksRequest
	(*GetTasksResponse)(nil),                 // 1: api.v1.task_tracker.tasks.GetTasksResponse
	(*CreateTasksRequest)(nil),               // 2: api.v1.task_tracker.tasks.CreateTasksRequest
	(*CreateTasksResponse)(nil),              // 3: api.v1.task_tracker.tasks.CreateTasksResponse
	(*UpdateTasksRequest)(nil),               // 4: api.v1.task_tracker.tasks.UpdateTasksRequest
	(*UpdateTasksResponse)(nil),              // 5: api.v1.task_tracker.tasks.UpdateTasksResponse
	(*DeleteTasksRequest)(nil),               // 6: api.v1.task_tracker.tasks.DeleteTasksRequest
	(*DeleteTasksResponse)(nil),              // 7: api.v1.task_tracker.tasks.DeleteTasksResponse
	(*CreateTasksRequest_TaskPrototype)(nil), // 8: api.v1.task_tracker.tasks.CreateTasksRequest.TaskPrototype
	(*UpdateTasksRequest_TaskPrototype)(nil), // 9: api.v1.task_tracker.tasks.UpdateTasksRequest.TaskPrototype
	(*Task)(nil),                             // 10: api.v1.task_tracker.tasks.Task
	(Priority)(0),                            // 11: api.v1.task_tracker.tasks.Priority
	(*timestamppb.Timestamp)(nil),            // 12: google.protobuf.Timestamp
}
var file_api_tasks_services_proto_depIdxs = []int32{
	10, // 0: api.v1.task_tracker.tasks.GetTasksResponse.tasks:type_name -> api.v1.task_tracker.tasks.Task
	8,  // 1: api.v1.task_tracker.tasks.CreateTasksRequest.tasks_to_create:type_name -> api.v1.task_tracker.tasks.CreateTasksRequest.TaskPrototype
	9,  // 2: api.v1.task_tracker.tasks.UpdateTasksRequest.tasks_to_update:type_name -> api.v1.task_tracker.tasks.UpdateTasksRequest.TaskPrototype
	11, // 3: api.v1.task_tracker.tasks.CreateTasksRequest.TaskPrototype.priority:type_name -> api.v1.task_tracker.tasks.Priority
	12, // 4: api.v1.task_tracker.tasks.CreateTasksRequest.TaskPrototype.start_time:type_name -> google.protobuf.Timestamp
	12, // 5: api.v1.task_tracker.tasks.CreateTasksRequest.TaskPrototype.finish_time:type_name -> google.protobuf.Timestamp
	11, // 6: api.v1.task_tracker.tasks.UpdateTasksRequest.TaskPrototype.priority:type_name -> api.v1.task_tracker.tasks.Priority
	12, // 7: api.v1.task_tracker.tasks.UpdateTasksRequest.TaskPrototype.start_time:type_name -> google.protobuf.Timestamp
	12, // 8: api.v1.task_tracker.tasks.UpdateTasksRequest.TaskPrototype.finish_time:type_name -> google.protobuf.Timestamp
	0,  // 9: api.v1.task_tracker.tasks.TaskService.GetTasks:input_type -> api.v1.task_tracker.tasks.GetTasksRequest
	2,  // 10: api.v1.task_tracker.tasks.TaskService.CreateTasks:input_type -> api.v1.task_tracker.tasks.CreateTasksRequest
	4,  // 11: api.v1.task_tracker.tasks.TaskService.UpdateTasks:input_type -> api.v1.task_tracker.tasks.UpdateTasksRequest
	6,  // 12: api.v1.task_tracker.tasks.TaskService.DeleteTasks:input_type -> api.v1.task_tracker.tasks.DeleteTasksRequest
	1,  // 13: api.v1.task_tracker.tasks.TaskService.GetTasks:output_type -> api.v1.task_tracker.tasks.GetTasksResponse
	3,  // 14: api.v1.task_tracker.tasks.TaskService.CreateTasks:output_type -> api.v1.task_tracker.tasks.CreateTasksResponse
	5,  // 15: api.v1.task_tracker.tasks.TaskService.UpdateTasks:output_type -> api.v1.task_tracker.tasks.UpdateTasksResponse
	7,  // 16: api.v1.task_tracker.tasks.TaskService.DeleteTasks:output_type -> api.v1.task_tracker.tasks.DeleteTasksResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_tasks_services_proto_init() }
func file_api_tasks_services_proto_init() {
	if File_api_tasks_services_proto != nil {
		return
	}
	file_api_tasks_models_proto_init()
	file_api_tasks_services_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tasks_services_proto_rawDesc), len(file_api_tasks_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tasks_services_proto_goTypes,
		DependencyIndexes: file_api_tasks_services_proto_depIdxs,
		MessageInfos:      file_api_tasks_services_proto_msgTypes,
	}.Build()
	File_api_tasks_services_proto = out.File
	file_api_tasks_services_proto_goTypes = nil
	file_api_tasks_services_proto_depIdxs = nil
}
