// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/boards/models.proto

package task_tracker_boards

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TopicIds      []int64                `protobuf:"varint,3,rep,packed,name=topic_ids,json=topicIds,proto3" json:"topic_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_api_boards_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_api_boards_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_api_boards_models_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Board) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Board) GetTopicIds() []int64 {
	if x != nil {
		return x.TopicIds
	}
	return nil
}

func (x *Board) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Board) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_boards_models_proto protoreflect.FileDescriptor

const file_api_boards_models_proto_rawDesc = "" +
	"\n" +
	"\x17api/boards/models.proto\x12\x1aapi.v1.task_tracker.boards\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttopic_ids\x18\x03 \x03(\x03R\btopicIds\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBSZQgithub.com/bogi-lyceya-44/task-tracker/internal/pb/api/boards;task_tracker_boardsb\x06proto3"

var (
	file_api_boards_models_proto_rawDescOnce sync.Once
	file_api_boards_models_proto_rawDescData []byte
)

func file_api_boards_models_proto_rawDescGZIP() []byte {
	file_api_boards_models_proto_rawDescOnce.Do(func() {
		file_api_boards_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_boards_models_proto_rawDesc), len(file_api_boards_models_proto_rawDesc)))
	})
	return file_api_boards_models_proto_rawDescData
}

var file_api_boards_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_boards_models_proto_goTypes = []any{
	(*Board)(nil),                 // 0: api.v1.task_tracker.boards.Board
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_api_boards_models_proto_depIdxs = []int32{
	1, // 0: api.v1.task_tracker.boards.Board.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: api.v1.task_tracker.boards.Board.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_boards_models_proto_init() }
func file_api_boards_models_proto_init() {
	if File_api_boards_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_boards_models_proto_rawDesc), len(file_api_boards_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_boards_models_proto_goTypes,
		DependencyIndexes: file_api_boards_models_proto_depIdxs,
		MessageInfos:      file_api_boards_models_proto_msgTypes,
	}.Build()
	File_api_boards_models_proto = out.File
	file_api_boards_models_proto_goTypes = nil
	file_api_boards_models_proto_depIdxs = nil
}
