// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/boards/services.proto

package task_tracker_boards

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetBoardsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBoardsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBoardsRequestMultiError, or nil if none found.
func (m *GetBoardsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBoardsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := GetBoardsRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetBoardsRequestMultiError(errors)
	}

	return nil
}

// GetBoardsRequestMultiError is an error wrapping multiple validation errors
// returned by GetBoardsRequest.ValidateAll() if the designated constraints
// aren't met.
type GetBoardsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBoardsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBoardsRequestMultiError) AllErrors() []error { return m }

// GetBoardsRequestValidationError is the validation error returned by
// GetBoardsRequest.Validate if the designated constraints aren't met.
type GetBoardsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBoardsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBoardsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBoardsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBoardsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBoardsRequestValidationError) ErrorName() string { return "GetBoardsRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetBoardsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBoardsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBoardsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBoardsRequestValidationError{}

// Validate checks the field values on GetBoardsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBoardsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBoardsResponseMultiError, or nil if none found.
func (m *GetBoardsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBoardsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBoards() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetBoardsResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetBoardsResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetBoardsResponseValidationError{
					field:  fmt.Sprintf("Boards[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetBoardsResponseMultiError(errors)
	}

	return nil
}

// GetBoardsResponseMultiError is an error wrapping multiple validation errors
// returned by GetBoardsResponse.ValidateAll() if the designated constraints
// aren't met.
type GetBoardsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBoardsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBoardsResponseMultiError) AllErrors() []error { return m }

// GetBoardsResponseValidationError is the validation error returned by
// GetBoardsResponse.Validate if the designated constraints aren't met.
type GetBoardsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBoardsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBoardsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBoardsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBoardsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBoardsResponseValidationError) ErrorName() string {
	return "GetBoardsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBoardsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBoardsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBoardsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBoardsResponseValidationError{}

// Validate checks the field values on CreateBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBoardsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBoardsRequestMultiError, or nil if none found.
func (m *CreateBoardsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBoardsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetBoardsToCreate()) < 1 {
		err := CreateBoardsRequestValidationError{
			field:  "BoardsToCreate",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetBoardsToCreate() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CreateBoardsRequestValidationError{
						field:  fmt.Sprintf("BoardsToCreate[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CreateBoardsRequestValidationError{
						field:  fmt.Sprintf("BoardsToCreate[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreateBoardsRequestValidationError{
					field:  fmt.Sprintf("BoardsToCreate[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CreateBoardsRequestMultiError(errors)
	}

	return nil
}

// CreateBoardsRequestMultiError is an error wrapping multiple validation
// errors returned by CreateBoardsRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateBoardsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBoardsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBoardsRequestMultiError) AllErrors() []error { return m }

// CreateBoardsRequestValidationError is the validation error returned by
// CreateBoardsRequest.Validate if the designated constraints aren't met.
type CreateBoardsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBoardsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBoardsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBoardsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBoardsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBoardsRequestValidationError) ErrorName() string {
	return "CreateBoardsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBoardsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBoardsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBoardsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBoardsRequestValidationError{}

// Validate checks the field values on CreateBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBoardsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBoardsResponseMultiError, or nil if none found.
func (m *CreateBoardsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBoardsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CreateBoardsResponseMultiError(errors)
	}

	return nil
}

// CreateBoardsResponseMultiError is an error wrapping multiple validation
// errors returned by CreateBoardsResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateBoardsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBoardsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBoardsResponseMultiError) AllErrors() []error { return m }

// CreateBoardsResponseValidationError is the validation error returned by
// CreateBoardsResponse.Validate if the designated constraints aren't met.
type CreateBoardsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBoardsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBoardsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBoardsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBoardsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBoardsResponseValidationError) ErrorName() string {
	return "CreateBoardsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBoardsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBoardsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBoardsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBoardsResponseValidationError{}

// Validate checks the field values on UpdateBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateBoardsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBoardsRequestMultiError, or nil if none found.
func (m *UpdateBoardsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBoardsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetBoardsToUpdate()) < 1 {
		err := UpdateBoardsRequestValidationError{
			field:  "BoardsToUpdate",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetBoardsToUpdate() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UpdateBoardsRequestValidationError{
						field:  fmt.Sprintf("BoardsToUpdate[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UpdateBoardsRequestValidationError{
						field:  fmt.Sprintf("BoardsToUpdate[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UpdateBoardsRequestValidationError{
					field:  fmt.Sprintf("BoardsToUpdate[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UpdateBoardsRequestMultiError(errors)
	}

	return nil
}

// UpdateBoardsRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateBoardsRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateBoardsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBoardsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBoardsRequestMultiError) AllErrors() []error { return m }

// UpdateBoardsRequestValidationError is the validation error returned by
// UpdateBoardsRequest.Validate if the designated constraints aren't met.
type UpdateBoardsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBoardsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBoardsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBoardsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBoardsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBoardsRequestValidationError) ErrorName() string {
	return "UpdateBoardsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBoardsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBoardsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBoardsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBoardsRequestValidationError{}

// Validate checks the field values on UpdateBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateBoardsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBoardsResponseMultiError, or nil if none found.
func (m *UpdateBoardsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBoardsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateBoardsResponseMultiError(errors)
	}

	return nil
}

// UpdateBoardsResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateBoardsResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateBoardsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBoardsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBoardsResponseMultiError) AllErrors() []error { return m }

// UpdateBoardsResponseValidationError is the validation error returned by
// UpdateBoardsResponse.Validate if the designated constraints aren't met.
type UpdateBoardsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBoardsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBoardsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBoardsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBoardsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBoardsResponseValidationError) ErrorName() string {
	return "UpdateBoardsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBoardsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBoardsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBoardsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBoardsResponseValidationError{}

// Validate checks the field values on DeleteBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteBoardsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBoardsRequestMultiError, or nil if none found.
func (m *DeleteBoardsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBoardsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := DeleteBoardsRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteBoardsRequestMultiError(errors)
	}

	return nil
}

// DeleteBoardsRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteBoardsRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteBoardsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBoardsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBoardsRequestMultiError) AllErrors() []error { return m }

// DeleteBoardsRequestValidationError is the validation error returned by
// DeleteBoardsRequest.Validate if the designated constraints aren't met.
type DeleteBoardsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBoardsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBoardsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBoardsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBoardsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBoardsRequestValidationError) ErrorName() string {
	return "DeleteBoardsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteBoardsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBoardsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBoardsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBoardsRequestValidationError{}

// Validate checks the field values on DeleteBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteBoardsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBoardsResponseMultiError, or nil if none found.
func (m *DeleteBoardsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBoardsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteBoardsResponseMultiError(errors)
	}

	return nil
}

// DeleteBoardsResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteBoardsResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteBoardsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBoardsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBoardsResponseMultiError) AllErrors() []error { return m }

// DeleteBoardsResponseValidationError is the validation error returned by
// DeleteBoardsResponse.Validate if the designated constraints aren't met.
type DeleteBoardsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBoardsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBoardsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBoardsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBoardsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBoardsResponseValidationError) ErrorName() string {
	return "DeleteBoardsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteBoardsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBoardsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBoardsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBoardsResponseValidationError{}

// Validate checks the field values on GetBoardContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBoardContentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBoardContentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBoardContentRequestMultiError, or nil if none found.
func (m *GetBoardContentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBoardContentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetIds()) < 1 {
		err := GetBoardContentRequestValidationError{
			field:  "Ids",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetBoardContentRequestMultiError(errors)
	}

	return nil
}

// GetBoardContentRequestMultiError is an error wrapping multiple validation
// errors returned by GetBoardContentRequest.ValidateAll() if the designated
// constraints aren't met.
type GetBoardContentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBoardContentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBoardContentRequestMultiError) AllErrors() []error { return m }

// GetBoardContentRequestValidationError is the validation error returned by
// GetBoardContentRequest.Validate if the designated constraints aren't met.
type GetBoardContentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBoardContentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBoardContentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBoardContentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBoardContentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBoardContentRequestValidationError) ErrorName() string {
	return "GetBoardContentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBoardContentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBoardContentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBoardContentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBoardContentRequestValidationError{}

// Validate checks the field values on GetBoardContentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBoardContentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBoardContentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBoardContentResponseMultiError, or nil if none found.
func (m *GetBoardContentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBoardContentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]int64, len(m.GetContentById()))
		i := 0
		for key := range m.GetContentById() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetContentById()[key]
			_ = val

			// no validation rules for ContentById[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, GetBoardContentResponseValidationError{
							field:  fmt.Sprintf("ContentById[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, GetBoardContentResponseValidationError{
							field:  fmt.Sprintf("ContentById[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return GetBoardContentResponseValidationError{
						field:  fmt.Sprintf("ContentById[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return GetBoardContentResponseMultiError(errors)
	}

	return nil
}

// GetBoardContentResponseMultiError is an error wrapping multiple validation
// errors returned by GetBoardContentResponse.ValidateAll() if the designated
// constraints aren't met.
type GetBoardContentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBoardContentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBoardContentResponseMultiError) AllErrors() []error { return m }

// GetBoardContentResponseValidationError is the validation error returned by
// GetBoardContentResponse.Validate if the designated constraints aren't met.
type GetBoardContentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBoardContentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBoardContentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBoardContentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBoardContentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBoardContentResponseValidationError) ErrorName() string {
	return "GetBoardContentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBoardContentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBoardContentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBoardContentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBoardContentResponseValidationError{}

// Validate checks the field values on GetAllBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAllBoardsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllBoardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllBoardsRequestMultiError, or nil if none found.
func (m *GetAllBoardsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllBoardsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetAllBoardsRequestMultiError(errors)
	}

	return nil
}

// GetAllBoardsRequestMultiError is an error wrapping multiple validation
// errors returned by GetAllBoardsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAllBoardsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllBoardsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllBoardsRequestMultiError) AllErrors() []error { return m }

// GetAllBoardsRequestValidationError is the validation error returned by
// GetAllBoardsRequest.Validate if the designated constraints aren't met.
type GetAllBoardsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllBoardsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllBoardsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllBoardsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllBoardsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllBoardsRequestValidationError) ErrorName() string {
	return "GetAllBoardsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllBoardsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllBoardsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllBoardsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllBoardsRequestValidationError{}

// Validate checks the field values on GetAllBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAllBoardsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAllBoardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAllBoardsResponseMultiError, or nil if none found.
func (m *GetAllBoardsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAllBoardsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBoards() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAllBoardsResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAllBoardsResponseValidationError{
						field:  fmt.Sprintf("Boards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAllBoardsResponseValidationError{
					field:  fmt.Sprintf("Boards[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAllBoardsResponseMultiError(errors)
	}

	return nil
}

// GetAllBoardsResponseMultiError is an error wrapping multiple validation
// errors returned by GetAllBoardsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetAllBoardsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAllBoardsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAllBoardsResponseMultiError) AllErrors() []error { return m }

// GetAllBoardsResponseValidationError is the validation error returned by
// GetAllBoardsResponse.Validate if the designated constraints aren't met.
type GetAllBoardsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAllBoardsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAllBoardsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAllBoardsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAllBoardsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAllBoardsResponseValidationError) ErrorName() string {
	return "GetAllBoardsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAllBoardsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAllBoardsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAllBoardsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAllBoardsResponseValidationError{}

// Validate checks the field values on BoardOrder with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BoardOrder) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardOrder with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BoardOrderMultiError, or
// nil if none found.
func (m *BoardOrder) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardOrder) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BoardId

	if m.GetPlace() <= 0 {
		err := BoardOrderValidationError{
			field:  "Place",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return BoardOrderMultiError(errors)
	}

	return nil
}

// BoardOrderMultiError is an error wrapping multiple validation errors
// returned by BoardOrder.ValidateAll() if the designated constraints aren't met.
type BoardOrderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardOrderMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardOrderMultiError) AllErrors() []error { return m }

// BoardOrderValidationError is the validation error returned by
// BoardOrder.Validate if the designated constraints aren't met.
type BoardOrderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardOrderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardOrderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardOrderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardOrderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardOrderValidationError) ErrorName() string { return "BoardOrderValidationError" }

// Error satisfies the builtin error interface
func (e BoardOrderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardOrder.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardOrderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardOrderValidationError{}

// Validate checks the field values on ChangeBoardOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ChangeBoardOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChangeBoardOrderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ChangeBoardOrderRequestMultiError, or nil if none found.
func (m *ChangeBoardOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ChangeBoardOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetChanges()) < 1 {
		err := ChangeBoardOrderRequestValidationError{
			field:  "Changes",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetChanges() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChangeBoardOrderRequestValidationError{
						field:  fmt.Sprintf("Changes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChangeBoardOrderRequestValidationError{
						field:  fmt.Sprintf("Changes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChangeBoardOrderRequestValidationError{
					field:  fmt.Sprintf("Changes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ChangeBoardOrderRequestMultiError(errors)
	}

	return nil
}

// ChangeBoardOrderRequestMultiError is an error wrapping multiple validation
// errors returned by ChangeBoardOrderRequest.ValidateAll() if the designated
// constraints aren't met.
type ChangeBoardOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChangeBoardOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChangeBoardOrderRequestMultiError) AllErrors() []error { return m }

// ChangeBoardOrderRequestValidationError is the validation error returned by
// ChangeBoardOrderRequest.Validate if the designated constraints aren't met.
type ChangeBoardOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChangeBoardOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChangeBoardOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChangeBoardOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChangeBoardOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChangeBoardOrderRequestValidationError) ErrorName() string {
	return "ChangeBoardOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ChangeBoardOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChangeBoardOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChangeBoardOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChangeBoardOrderRequestValidationError{}

// Validate checks the field values on ChangeBoardOrderResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ChangeBoardOrderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChangeBoardOrderResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ChangeBoardOrderResponseMultiError, or nil if none found.
func (m *ChangeBoardOrderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ChangeBoardOrderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ChangeBoardOrderResponseMultiError(errors)
	}

	return nil
}

// ChangeBoardOrderResponseMultiError is an error wrapping multiple validation
// errors returned by ChangeBoardOrderResponse.ValidateAll() if the designated
// constraints aren't met.
type ChangeBoardOrderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChangeBoardOrderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChangeBoardOrderResponseMultiError) AllErrors() []error { return m }

// ChangeBoardOrderResponseValidationError is the validation error returned by
// ChangeBoardOrderResponse.Validate if the designated constraints aren't met.
type ChangeBoardOrderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChangeBoardOrderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChangeBoardOrderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChangeBoardOrderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChangeBoardOrderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChangeBoardOrderResponseValidationError) ErrorName() string {
	return "ChangeBoardOrderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ChangeBoardOrderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChangeBoardOrderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChangeBoardOrderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChangeBoardOrderResponseValidationError{}

// Validate checks the field values on GetBoardOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBoardOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBoardOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBoardOrderRequestMultiError, or nil if none found.
func (m *GetBoardOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBoardOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetBoardOrderRequestMultiError(errors)
	}

	return nil
}

// GetBoardOrderRequestMultiError is an error wrapping multiple validation
// errors returned by GetBoardOrderRequest.ValidateAll() if the designated
// constraints aren't met.
type GetBoardOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBoardOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBoardOrderRequestMultiError) AllErrors() []error { return m }

// GetBoardOrderRequestValidationError is the validation error returned by
// GetBoardOrderRequest.Validate if the designated constraints aren't met.
type GetBoardOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBoardOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBoardOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBoardOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBoardOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBoardOrderRequestValidationError) ErrorName() string {
	return "GetBoardOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBoardOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBoardOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBoardOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBoardOrderRequestValidationError{}

// Validate checks the field values on GetBoardOrderResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBoardOrderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBoardOrderResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBoardOrderResponseMultiError, or nil if none found.
func (m *GetBoardOrderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBoardOrderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Order

	if len(errors) > 0 {
		return GetBoardOrderResponseMultiError(errors)
	}

	return nil
}

// GetBoardOrderResponseMultiError is an error wrapping multiple validation
// errors returned by GetBoardOrderResponse.ValidateAll() if the designated
// constraints aren't met.
type GetBoardOrderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBoardOrderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBoardOrderResponseMultiError) AllErrors() []error { return m }

// GetBoardOrderResponseValidationError is the validation error returned by
// GetBoardOrderResponse.Validate if the designated constraints aren't met.
type GetBoardOrderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBoardOrderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBoardOrderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBoardOrderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBoardOrderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBoardOrderResponseValidationError) ErrorName() string {
	return "GetBoardOrderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBoardOrderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBoardOrderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBoardOrderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBoardOrderResponseValidationError{}

// Validate checks the field values on CreateBoardsRequest_BoardPrototype with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CreateBoardsRequest_BoardPrototype) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBoardsRequest_BoardPrototype
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// CreateBoardsRequest_BoardPrototypeMultiError, or nil if none found.
func (m *CreateBoardsRequest_BoardPrototype) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBoardsRequest_BoardPrototype) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateBoardsRequest_BoardPrototypeValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateBoardsRequest_BoardPrototypeMultiError(errors)
	}

	return nil
}

// CreateBoardsRequest_BoardPrototypeMultiError is an error wrapping multiple
// validation errors returned by
// CreateBoardsRequest_BoardPrototype.ValidateAll() if the designated
// constraints aren't met.
type CreateBoardsRequest_BoardPrototypeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBoardsRequest_BoardPrototypeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBoardsRequest_BoardPrototypeMultiError) AllErrors() []error { return m }

// CreateBoardsRequest_BoardPrototypeValidationError is the validation error
// returned by CreateBoardsRequest_BoardPrototype.Validate if the designated
// constraints aren't met.
type CreateBoardsRequest_BoardPrototypeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBoardsRequest_BoardPrototypeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBoardsRequest_BoardPrototypeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBoardsRequest_BoardPrototypeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBoardsRequest_BoardPrototypeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBoardsRequest_BoardPrototypeValidationError) ErrorName() string {
	return "CreateBoardsRequest_BoardPrototypeValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBoardsRequest_BoardPrototypeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBoardsRequest_BoardPrototype.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBoardsRequest_BoardPrototypeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBoardsRequest_BoardPrototypeValidationError{}

// Validate checks the field values on UpdateBoardsRequest_BoardPrototype with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateBoardsRequest_BoardPrototype) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBoardsRequest_BoardPrototype
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateBoardsRequest_BoardPrototypeMultiError, or nil if none found.
func (m *UpdateBoardsRequest_BoardPrototype) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBoardsRequest_BoardPrototype) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if m.Name != nil {

		if utf8.RuneCountInString(m.GetName()) < 1 {
			err := UpdateBoardsRequest_BoardPrototypeValidationError{
				field:  "Name",
				reason: "value length must be at least 1 runes",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return UpdateBoardsRequest_BoardPrototypeMultiError(errors)
	}

	return nil
}

// UpdateBoardsRequest_BoardPrototypeMultiError is an error wrapping multiple
// validation errors returned by
// UpdateBoardsRequest_BoardPrototype.ValidateAll() if the designated
// constraints aren't met.
type UpdateBoardsRequest_BoardPrototypeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBoardsRequest_BoardPrototypeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBoardsRequest_BoardPrototypeMultiError) AllErrors() []error { return m }

// UpdateBoardsRequest_BoardPrototypeValidationError is the validation error
// returned by UpdateBoardsRequest_BoardPrototype.Validate if the designated
// constraints aren't met.
type UpdateBoardsRequest_BoardPrototypeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBoardsRequest_BoardPrototypeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBoardsRequest_BoardPrototypeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBoardsRequest_BoardPrototypeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBoardsRequest_BoardPrototypeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBoardsRequest_BoardPrototypeValidationError) ErrorName() string {
	return "UpdateBoardsRequest_BoardPrototypeValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBoardsRequest_BoardPrototypeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBoardsRequest_BoardPrototype.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBoardsRequest_BoardPrototypeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBoardsRequest_BoardPrototypeValidationError{}

// Validate checks the field values on GetBoardContentResponse_BoardContent
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *GetBoardContentResponse_BoardContent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBoardContentResponse_BoardContent
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetBoardContentResponse_BoardContentMultiError, or nil if none found.
func (m *GetBoardContentResponse_BoardContent) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBoardContentResponse_BoardContent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTopics() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetBoardContentResponse_BoardContentValidationError{
						field:  fmt.Sprintf("Topics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetBoardContentResponse_BoardContentValidationError{
						field:  fmt.Sprintf("Topics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetBoardContentResponse_BoardContentValidationError{
					field:  fmt.Sprintf("Topics[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetBoardContentResponse_BoardContentMultiError(errors)
	}

	return nil
}

// GetBoardContentResponse_BoardContentMultiError is an error wrapping multiple
// validation errors returned by
// GetBoardContentResponse_BoardContent.ValidateAll() if the designated
// constraints aren't met.
type GetBoardContentResponse_BoardContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBoardContentResponse_BoardContentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBoardContentResponse_BoardContentMultiError) AllErrors() []error { return m }

// GetBoardContentResponse_BoardContentValidationError is the validation error
// returned by GetBoardContentResponse_BoardContent.Validate if the designated
// constraints aren't met.
type GetBoardContentResponse_BoardContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBoardContentResponse_BoardContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBoardContentResponse_BoardContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBoardContentResponse_BoardContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBoardContentResponse_BoardContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBoardContentResponse_BoardContentValidationError) ErrorName() string {
	return "GetBoardContentResponse_BoardContentValidationError"
}

// Error satisfies the builtin error interface
func (e GetBoardContentResponse_BoardContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBoardContentResponse_BoardContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBoardContentResponse_BoardContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBoardContentResponse_BoardContentValidationError{}
