services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  task_tracker:
    image: ghcr.io/bogi-lyceya-44/task-tracker:master
    container_name: task_tracker
    environment:
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable&search_path=task_tracker
      GATEWAY_HOST: 0.0.0.0
      GATEWAY_PORT: 7000
      GRPC_HOST: 0.0.0.0
      GRPC_PORT: 7001
    ports:
      - 7000:7000
      - 7001:7001
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
