// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/topics/models.proto

package task_tracker_topics

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TaskIds       []int64                `protobuf:"varint,3,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_api_topics_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_api_topics_models_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *Topic) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Topic) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_api_topics_models_proto protoreflect.FileDescriptor

const file_api_topics_models_proto_rawDesc = "" +
	"\n" +
	"\x17api/topics/models.proto\x12\x1aapi.v1.task_tracker.topics\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\btask_ids\x18\x03 \x03(\x03R\ataskIds\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBCZAgithub.com/bogi-lyceya-44/task-tracker/topics;task_tracker_topicsb\x06proto3"

var (
	file_api_topics_models_proto_rawDescOnce sync.Once
	file_api_topics_models_proto_rawDescData []byte
)

func file_api_topics_models_proto_rawDescGZIP() []byte {
	file_api_topics_models_proto_rawDescOnce.Do(func() {
		file_api_topics_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_topics_models_proto_rawDesc), len(file_api_topics_models_proto_rawDesc)))
	})
	return file_api_topics_models_proto_rawDescData
}

var file_api_topics_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_topics_models_proto_goTypes = []any{
	(*Topic)(nil),                 // 0: api.v1.task_tracker.topics.Topic
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_api_topics_models_proto_depIdxs = []int32{
	1, // 0: api.v1.task_tracker.topics.Topic.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: api.v1.task_tracker.topics.Topic.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_topics_models_proto_init() }
func file_api_topics_models_proto_init() {
	if File_api_topics_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_topics_models_proto_rawDesc), len(file_api_topics_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_topics_models_proto_goTypes,
		DependencyIndexes: file_api_topics_models_proto_depIdxs,
		MessageInfos:      file_api_topics_models_proto_msgTypes,
	}.Build()
	File_api_topics_models_proto = out.File
	file_api_topics_models_proto_goTypes = nil
	file_api_topics_models_proto_depIdxs = nil
}
