// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/topics/services.proto

package task_tracker_topics

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicsRequest) Reset() {
	*x = GetTopicsRequest{}
	mi := &file_api_topics_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsRequest) ProtoMessage() {}

func (x *GetTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetTopicsRequest) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopicsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicsResponse) Reset() {
	*x = GetTopicsResponse{}
	mi := &file_api_topics_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsResponse) ProtoMessage() {}

func (x *GetTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetTopicsResponse) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type CreateTopicsRequest struct {
	state          protoimpl.MessageState                `protogen:"open.v1"`
	TopicsToCreate []*CreateTopicsRequest_TopicPrototype `protobuf:"bytes,1,rep,name=topics_to_create,json=topicsToCreate,proto3" json:"topics_to_create,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTopicsRequest) Reset() {
	*x = CreateTopicsRequest{}
	mi := &file_api_topics_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicsRequest) ProtoMessage() {}

func (x *CreateTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicsRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicsRequest) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTopicsRequest) GetTopicsToCreate() []*CreateTopicsRequest_TopicPrototype {
	if x != nil {
		return x.TopicsToCreate
	}
	return nil
}

type CreateTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicsResponse) Reset() {
	*x = CreateTopicsResponse{}
	mi := &file_api_topics_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicsResponse) ProtoMessage() {}

func (x *CreateTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicsResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicsResponse) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTopicsResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UpdateTopicsRequest struct {
	state          protoimpl.MessageState                `protogen:"open.v1"`
	TopicsToUpdate []*UpdateTopicsRequest_TopicPrototype `protobuf:"bytes,1,rep,name=topics_to_update,json=topicsToUpdate,proto3" json:"topics_to_update,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTopicsRequest) Reset() {
	*x = UpdateTopicsRequest{}
	mi := &file_api_topics_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicsRequest) ProtoMessage() {}

func (x *UpdateTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTopicsRequest) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTopicsRequest) GetTopicsToUpdate() []*UpdateTopicsRequest_TopicPrototype {
	if x != nil {
		return x.TopicsToUpdate
	}
	return nil
}

type UpdateTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicsResponse) Reset() {
	*x = UpdateTopicsResponse{}
	mi := &file_api_topics_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicsResponse) ProtoMessage() {}

func (x *UpdateTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicsResponse.ProtoReflect.Descriptor instead.
func (*UpdateTopicsResponse) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{5}
}

type DeleteTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicsRequest) Reset() {
	*x = DeleteTopicsRequest{}
	mi := &file_api_topics_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicsRequest) ProtoMessage() {}

func (x *DeleteTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicsRequest.ProtoReflect.Descriptor instead.
func (*DeleteTopicsRequest) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTopicsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicsResponse) Reset() {
	*x = DeleteTopicsResponse{}
	mi := &file_api_topics_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicsResponse) ProtoMessage() {}

func (x *DeleteTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicsResponse.ProtoReflect.Descriptor instead.
func (*DeleteTopicsResponse) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{7}
}

type CreateTopicsRequest_TopicPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TaskIds       []int64                `protobuf:"varint,2,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicsRequest_TopicPrototype) Reset() {
	*x = CreateTopicsRequest_TopicPrototype{}
	mi := &file_api_topics_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicsRequest_TopicPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicsRequest_TopicPrototype) ProtoMessage() {}

func (x *CreateTopicsRequest_TopicPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicsRequest_TopicPrototype.ProtoReflect.Descriptor instead.
func (*CreateTopicsRequest_TopicPrototype) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateTopicsRequest_TopicPrototype) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicsRequest_TopicPrototype) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type UpdateTopicsRequest_TopicPrototype struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	TaskIds       []int64                `protobuf:"varint,3,rep,packed,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicsRequest_TopicPrototype) Reset() {
	*x = UpdateTopicsRequest_TopicPrototype{}
	mi := &file_api_topics_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicsRequest_TopicPrototype) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicsRequest_TopicPrototype) ProtoMessage() {}

func (x *UpdateTopicsRequest_TopicPrototype) ProtoReflect() protoreflect.Message {
	mi := &file_api_topics_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicsRequest_TopicPrototype.ProtoReflect.Descriptor instead.
func (*UpdateTopicsRequest_TopicPrototype) Descriptor() ([]byte, []int) {
	return file_api_topics_services_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateTopicsRequest_TopicPrototype) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTopicsRequest_TopicPrototype) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTopicsRequest_TopicPrototype) GetTaskIds() []int64 {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

var File_api_topics_services_proto protoreflect.FileDescriptor

const file_api_topics_services_proto_rawDesc = "" +
	"\n" +
	"\x19api/topics/services.proto\x12\x1aapi.v1.task_tracker.topics\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x17api/topics/models.proto\".\n" +
	"\x10GetTopicsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x03B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"N\n" +
	"\x11GetTopicsResponse\x129\n" +
	"\x06topics\x18\x01 \x03(\v2!.api.v1.task_tracker.topics.TopicR\x06topics\"\xd3\x01\n" +
	"\x13CreateTopicsRequest\x12r\n" +
	"\x10topics_to_create\x18\x01 \x03(\v2>.api.v1.task_tracker.topics.CreateTopicsRequest.TopicPrototypeB\b\xfaB\x05\x92\x01\x02\b\x01R\x0etopicsToCreate\x1aH\n" +
	"\x0eTopicPrototype\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\x03R\ataskIds\"(\n" +
	"\x14CreateTopicsResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\xf1\x01\n" +
	"\x13UpdateTopicsRequest\x12r\n" +
	"\x10topics_to_update\x18\x01 \x03(\v2>.api.v1.task_tracker.topics.UpdateTopicsRequest.TopicPrototypeB\b\xfaB\x05\x92\x01\x02\b\x01R\x0etopicsToUpdate\x1af\n" +
	"\x0eTopicPrototype\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\btask_ids\x18\x03 \x03(\x03R\ataskIdsB\a\n" +
	"\x05_name\"\x16\n" +
	"\x14UpdateTopicsResponse\"1\n" +
	"\x13DeleteTopicsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x03B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\x16\n" +
	"\x14DeleteTopicsResponse2\xda\x04\n" +
	"\fTopicService\x12\x87\x01\n" +
	"\tGetTopics\x12,.api.v1.task_tracker.topics.GetTopicsRequest\x1a-.api.v1.task_tracker.topics.GetTopicsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/get_topics\x12\x93\x01\n" +
	"\fCreateTopics\x12/.api.v1.task_tracker.topics.CreateTopicsRequest\x1a0.api.v1.task_tracker.topics.CreateTopicsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/create_topics\x12\x93\x01\n" +
	"\fUpdateTopics\x12/.api.v1.task_tracker.topics.UpdateTopicsRequest\x1a0.api.v1.task_tracker.topics.UpdateTopicsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/update_topics\x12\x93\x01\n" +
	"\fDeleteTopics\x12/.api.v1.task_tracker.topics.DeleteTopicsRequest\x1a0.api.v1.task_tracker.topics.DeleteTopicsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/delete_topicsBSZQgithub.com/bogi-lyceya-44/task-tracker/internal/pb/api/topics;task_tracker_topicsb\x06proto3"

var (
	file_api_topics_services_proto_rawDescOnce sync.Once
	file_api_topics_services_proto_rawDescData []byte
)

func file_api_topics_services_proto_rawDescGZIP() []byte {
	file_api_topics_services_proto_rawDescOnce.Do(func() {
		file_api_topics_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_topics_services_proto_rawDesc), len(file_api_topics_services_proto_rawDesc)))
	})
	return file_api_topics_services_proto_rawDescData
}

var file_api_topics_services_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_topics_services_proto_goTypes = []any{
	(*GetTopicsRequest)(nil),                   // 0: api.v1.task_tracker.topics.GetTopicsRequest
	(*GetTopicsResponse)(nil),                  // 1: api.v1.task_tracker.topics.GetTopicsResponse
	(*CreateTopicsRequest)(nil),                // 2: api.v1.task_tracker.topics.CreateTopicsRequest
	(*CreateTopicsResponse)(nil),               // 3: api.v1.task_tracker.topics.CreateTopicsResponse
	(*UpdateTopicsRequest)(nil),                // 4: api.v1.task_tracker.topics.UpdateTopicsRequest
	(*UpdateTopicsResponse)(nil),               // 5: api.v1.task_tracker.topics.UpdateTopicsResponse
	(*DeleteTopicsRequest)(nil),                // 6: api.v1.task_tracker.topics.DeleteTopicsRequest
	(*DeleteTopicsResponse)(nil),               // 7: api.v1.task_tracker.topics.DeleteTopicsResponse
	(*CreateTopicsRequest_TopicPrototype)(nil), // 8: api.v1.task_tracker.topics.CreateTopicsRequest.TopicPrototype
	(*UpdateTopicsRequest_TopicPrototype)(nil), // 9: api.v1.task_tracker.topics.UpdateTopicsRequest.TopicPrototype
	(*Topic)(nil),                              // 10: api.v1.task_tracker.topics.Topic
}
var file_api_topics_services_proto_depIdxs = []int32{
	10, // 0: api.v1.task_tracker.topics.GetTopicsResponse.topics:type_name -> api.v1.task_tracker.topics.Topic
	8,  // 1: api.v1.task_tracker.topics.CreateTopicsRequest.topics_to_create:type_name -> api.v1.task_tracker.topics.CreateTopicsRequest.TopicPrototype
	9,  // 2: api.v1.task_tracker.topics.UpdateTopicsRequest.topics_to_update:type_name -> api.v1.task_tracker.topics.UpdateTopicsRequest.TopicPrototype
	0,  // 3: api.v1.task_tracker.topics.TopicService.GetTopics:input_type -> api.v1.task_tracker.topics.GetTopicsRequest
	2,  // 4: api.v1.task_tracker.topics.TopicService.CreateTopics:input_type -> api.v1.task_tracker.topics.CreateTopicsRequest
	4,  // 5: api.v1.task_tracker.topics.TopicService.UpdateTopics:input_type -> api.v1.task_tracker.topics.UpdateTopicsRequest
	6,  // 6: api.v1.task_tracker.topics.TopicService.DeleteTopics:input_type -> api.v1.task_tracker.topics.DeleteTopicsRequest
	1,  // 7: api.v1.task_tracker.topics.TopicService.GetTopics:output_type -> api.v1.task_tracker.topics.GetTopicsResponse
	3,  // 8: api.v1.task_tracker.topics.TopicService.CreateTopics:output_type -> api.v1.task_tracker.topics.CreateTopicsResponse
	5,  // 9: api.v1.task_tracker.topics.TopicService.UpdateTopics:output_type -> api.v1.task_tracker.topics.UpdateTopicsResponse
	7,  // 10: api.v1.task_tracker.topics.TopicService.DeleteTopics:output_type -> api.v1.task_tracker.topics.DeleteTopicsResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_topics_services_proto_init() }
func file_api_topics_services_proto_init() {
	if File_api_topics_services_proto != nil {
		return
	}
	file_api_topics_models_proto_init()
	file_api_topics_services_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_topics_services_proto_rawDesc), len(file_api_topics_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_topics_services_proto_goTypes,
		DependencyIndexes: file_api_topics_services_proto_depIdxs,
		MessageInfos:      file_api_topics_services_proto_msgTypes,
	}.Build()
	File_api_topics_services_proto = out.File
	file_api_topics_services_proto_goTypes = nil
	file_api_topics_services_proto_depIdxs = nil
}
